name: coolcat

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:

  build-site:
    runs-on: ubuntu-latest
    steps:

      - name: Initialise DEPLOY variable
        run: |
          if [[ '${{ github.ref }}' == 'refs/heads/main' ]]; then
             echo "COOLCAT_DEPLOY=true" >> "$GITHUB_ENV"
          fi

      - name: Install build dependencies
        run: |
          sudo apt-get update
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo dpkg -i pandoc-2.18-1-amd64.deb
          sudo apt-get install -y texlive-base texlive-latex-extra texlive-pictures pdf2svg

      - name: Checkout coolcat
        uses: actions/checkout@v2

      - name: Build html doc
        run: make

      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: ${{ success() && env.COOLCAT_DEPLOY }}

        with:
          branch: gh-pages
          folder: build/
          git-config-name: Github Actions
